name: "Test & Lint"

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        luaVersion: ["5.4.4", "luajit-2.1.0-beta3"]

    steps:
      - uses: "actions/checkout@master"

      - uses: "leafo/gh-actions-lua@v9"
        with:
          luaVersion: "${{ matrix.luaVersion }}"

      - name: "Test"
        run: |
          ./test.sh

  Lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Lint with StyLua"
        uses: "JohnnyMorganz/stylua-action@1.0.0"
        with:
          token: "${{ secrets.STYLUA_GITHUB_TOKEN }}"
          args: "--check ."
